from __future__ import annotations

import re
from pathlib import Path

from create_submission_candidate_manuscripts import rebuild_docx


BASE = Path(__file__).resolve().parents[1]
ROOT = BASE
PKG = ROOT / "manuscript"
REFERENCE_BLOCK = ROOT / "references" / "paper3_verified_reference_block.md"

PAPER_FILES = [
    PKG / "paper_3_decision_focused_vpp_bidding.md",
    ROOT / "manuscript" / "submission_candidate" / "paper_3_decision_focused_vpp_bidding.md",
]


REPLACEMENTS = [
    (
        "Decision-focused learning provides a principled framework for this problem. Instead of treating optimization as a downstream black box, the learning process incorporates decision loss, regret, or differentiable optimization layers.",
        "Decision-focused learning provides a principled framework for this problem. Instead of treating optimization as a downstream black box, the learning process can incorporate decision loss, regret, or optimization-aware surrogates, following prescriptive analytics, smart predict-then-optimize, and task-based learning work [1]-[5].",
    ),
    (
        "This perspective is well aligned with computer-science research on predict-and-optimize, differentiable optimization, and task-based learning.",
        "This perspective is well aligned with computer-science research on predict-and-optimize, differentiable optimization, and task-based learning [2]-[5].",
    ),
    (
        "Virtual power plants aggregate distributed resources to provide market services such as energy trading, demand response, reserve support, and renewable integration.",
        "Virtual power plants aggregate distributed resources to provide market services such as energy trading, demand response, reserve support, and renewable integration [12], [13].",
    ),
    (
        "Existing work often formulates bidding or scheduling as deterministic, stochastic, robust, or reinforcement-learning optimization.",
        "Existing work often formulates bidding or scheduling as deterministic, stochastic, robust, or reinforcement-learning optimization, including stochastic-programming and strategic-bidding formulations for VPP markets [14], [15].",
    ),
    (
        "Predictive models are commonly evaluated with statistical error metrics.",
        "Predictive models are commonly evaluated with statistical error metrics, but electricity-price forecasting benchmarks show that statistical accuracy alone is only one layer of market-facing evaluation [10], [11].",
    ),
    (
        "However, prescriptive analytics shows that prediction quality is best evaluated by downstream decisions when the ultimate objective is operational.",
        "However, prescriptive analytics shows that prediction quality is best evaluated by downstream decisions when the ultimate objective is operational [1].",
    ),
    (
        "Smart predict-and-optimize methods, differentiable optimization layers, and task-based end-to-end learning provide tools for aligning model training with optimization performance.",
        "Smart predict-and-optimize methods, optimization-aware learning layers, task-based end-to-end learning, and decision-focused combinatorial optimization provide tools for aligning model training with optimization performance [2]-[5].",
    ),
    (
        "In machine-learning-based pipelines, uncertainty can be generated by quantile forecasts, ensembles, Bayesian methods, or conformal prediction.",
        "In machine-learning-based pipelines, uncertainty can be generated by quantile forecasts, ensembles, Bayesian methods, or conformal prediction [8], [9], [11].",
    ),
    (
        "A simplified objective is:",
        "A simplified objective is based on a convex or surrogate decision layer, using standard optimization notation [7]:",
    ),
    (
        "The model does not optimize only expected revenue. A risk-aware decision layer uses CVaR or quantile-based downside constraints:",
        "The implemented protocol does not optimize only expected revenue. A risk-aware decision layer uses CVaR or quantile-based downside constraints, following the standard CVaR optimization formulation [6]:",
    ),
    (
        "The public decision substrate uses OPSD hourly day-ahead price, load, wind, and solar series for DE-LU, DK1, DK2, and Great Britain.",
        "The public decision substrate uses OPSD hourly day-ahead price, load, wind, and solar series for DE-LU, DK1, DK2, and Great Britain [16].",
    ),
    (
        "The final forecast-coupled layer connects the Paper 1 conformal electricity-price forecasts and a Paper 2-style lag-calendar net-load forecast to the same VPP simulator.",
        "The final forecast-coupled layer connects the Paper 1 conformal electricity-price forecasts and a Paper 2-style lag-calendar net-load forecast to the same VPP simulator, so probabilistic forecasting evidence is evaluated through downstream decision value [8]-[11].",
    ),
    (
        "The historical baselines include same-day hindsight, previous-day forecast-then-optimize, rolling 28-day mean forecast-then-optimize, and robust quantile forecast-then-optimize.",
        "The historical baselines include same-day hindsight, previous-day forecast-then-optimize, rolling 28-day mean forecast-then-optimize, and robust quantile forecast-then-optimize [1], [2].",
    ),
    (
        "The decision-focused variants choose charge and discharge scoring coefficients on a training or adaptation period by directly optimizing realized revenue or a revenue-plus-CVaR objective.",
        "The decision-focused variants choose charge and discharge scoring coefficients on a training or adaptation period by directly optimizing realized revenue or a revenue-plus-CVaR objective [1], [2], [6].",
    ),
    (
        "Decision metrics: total revenue, average daily profit, regret against hindsight optimum, imbalance penalty, downside revenue, CVaR, loss days, and risk-adjusted return.",
        "Decision metrics: total revenue, average daily profit, regret against hindsight optimum, imbalance penalty, downside revenue, CVaR, loss days, and risk-adjusted return [1], [2], [6].",
    ),
    (
        "The OPSD public decision benchmark is reproducible from `run_public_opsd_baselines.py`;",
        "The OPSD public decision benchmark [16] is reproducible from `run_public_opsd_baselines.py`;",
    ),
]


CURRENT_POLICY_SEARCH_SECTION = """### 4.3 Auditable decision-focused policy search

The reproducible implementation uses a transparent surrogate decision-focused layer rather than an end-to-end neural optimizer. Candidate policies score charge and discharge hours with historical price mean, price volatility, and net-load shape features. Policy coefficients are selected on chronological training and validation days by maximizing realized decision value or a revenue-plus-CVaR objective, and the selected coefficients are then frozen before held-out test evaluation.

This design tests the predict-and-optimize hypothesis without relying on an opaque proprietary market engine. The decision objective is:

L_decision = -J(u_theta; y) - lambda_r CVaR10(u_theta),

where J is realized daily decision value in the public simulator and lambda_r controls risk aversion. Differentiable optimization layers remain a natural extension, but the current manuscript claims only the public, auditable surrogate policy-search evidence reported in the experiments.

"""


def apply_once(text: str, old: str, new: str) -> str:
    if new in text:
        return text
    if old not in text:
        return text
    return text.replace(old, new, 1)


def replace_references(text: str) -> str:
    block = REFERENCE_BLOCK.read_text(encoding="utf-8").strip()
    if "## References" not in text:
        return text.rstrip() + "\n\n" + block + "\n"
    return re.sub(r"\n## References\n.*\Z", "\n" + block + "\n", text, flags=re.S)


def normalize_policy_search_claim(text: str) -> str:
    return re.sub(
        r"### 4\.3 .*?\n\n.*?(?=\n### 4\.4 Risk-aware scenario selection)",
        CURRENT_POLICY_SEARCH_SECTION,
        text,
        flags=re.S,
    )


def main() -> None:
    for path in PAPER_FILES:
        text = path.read_text(encoding="utf-8")
        for old, new in REPLACEMENTS:
            text = apply_once(text, old, new)
        text = normalize_policy_search_claim(text)
        text = replace_references(text)
        path.write_text(text, encoding="utf-8")
        rebuild_docx(path, text)
        print(path)
        print(path.with_suffix(".docx"))


if __name__ == "__main__":
    main()
